name: Run Tests

on: 
  pull_request:  # Trigger the action when a PR is opened or updated

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu environment 

    steps:
      - uses: actions/checkout@v4  # Check out repository code

      - name: Set up Node.js  # Example for Node.js - adapt for your language
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
